### ISSUE TITLE
Please do not include external libs

### ISSUE THREAD

**Issue by pcav** [yojiyojiyoji/oam_qgis3_express#1] opened 2019-04-11 03:58 UTC
Rather, warn users that they should install it separately, according to their operating system.
See other plugins.
Thanks.

**Comment by yojiyojiyoji** [comment] 2019-04-19 13:42
Are you still using debian sid? What kind of errors have you got?

Problem is that I am mainly writing codes for normal OSGeo4W (Windows 10) users, who don’t have enough knowledge on software development, installation of external libraries, etc. (Maybe you know about this, but Windows does not include a system supported installation of Python.)

If OSgeo4W supports pip, I may be able to use it, but I will have to check if there is no side-effect with it, anyway…

**Comment by yojiyojiyoji** [comment] 2019-04-19 19:12
Additionally, it is noted that I’ve confirmed that this plugin was working on Win10, Linux Mint (18.3 and 19.1), and MacOS10.14 (Mojave).

**Comment by yojiyojiyoji** [comment] 2019-04-19 20:29
One more comment:
Basically, I am not using any platform-dependent python libraries in this plugin.

**Comment by pcav** [comment] 2019-04-20 05:45
Hi, I'm refferring to https://github.com/yojiyojiyoji/oam_qgis3_express/tree/master/ext_libs
heers.

**Comment by yojiyojiyoji** [comment] 2019-04-20 22:55
I know. As wrote above, these libraries are supposed to be platform independent, because these are all in script format, not binary format. Indeed I’ve already confirmed that it works on 
the operating systems mentioned above (Win10, Linux Mint 18.3 and 19.1, and MacOS 10.14, Mojave).

**Comment by yojiyojiyoji** [comment] 2019-04-21 00:11
Anyway, please just read all the past comments, which I wrote in this issue, from the beginning.
https://github.com/yojiyojiyoji/oam_qgis3_express/issues/1

The essence is that I would like to create a sort of virtual environment for this plugin, to insulate it from the other applications or plugins, as well as improving the compatibility for various operating systems. (If I let the users to install external libraries separately, they must share them with other applications or plugins. I don’t really think it is good solution.) 
At the same time, I think we have to pay attention to the normal OSGeo4W (Windows 10) users, which is slightly different from *.nix environment.

**Comment by pcav** [comment] 2019-04-23 06:45
Hi,
I have read it. I'm well aware of the issue. Our position is to avoid bundling libraries, as this causes more problems in the long run, especially when you consider that we now have over 1,000 plugins to manage. Many other plugins have the same issue, and followed the standard recommendation.
The proper solution will be to implement an automatism for letting the user download and install the needed libraries at the installation of the plugin. Your help for implementing this will be most welcomed.
Thanks for understanding.

**Comment by yojiyojiyoji** [comment] 2019-04-25 23:17
So, please just let me do the modification in the next version, since I don’t think I can spend so much time on this plugin at the moment. (I am working as a volunteer.) At the same time, I need to ask someone else to test on different operating systems, once more. (Actually, we already have spent a lot of time on testing on different operating systems, including Debian-SID and MacOS, for this release. So, I don’t like you to deny it so easily. To be honest, it is extremely stressful and unreasonable to test on these platforms from the beginning, simply to separate external libraries.) I also think it is better to let users to use the plugin as soon as possible, and get the feedback before the next version, even if it was a little erroneous. (This is still Experimental Version 0.1.)

**Comment by pcav** [comment] 2019-04-28 11:08
Hi, I understand well your concerns. However, looking from a broader perspective (remember, I have to manage more than 1,000 plugins, and I do it voluntarily in my spare time) I rest convinced that the best option is to go as indicated, letting users install their own libs. You do not need to test each OS version, you can leave users do this for you. This is quite acceptable, especially for an experimental plugin.
Thanks for understanding.

**Comment by yojiyojiyoji** [comment] 2019-04-28 23:52
I guess you don’t really understand what I am saying. Please read my comment a little more carefully.
As I wrote, I am saying I will separate the external libraries, but it will be in the next version (release), because I don’t have enough time right now. What you have to do is just to wait until next release, simply after enabling public access of current version. I will separate the external libraries and upload it later. There is nothing more to do.

**Comment by pcav** [comment] 2019-04-29 06:41
Please be gentle with me. I have fully understood your writing.

**Comment by NyakudyaA** [comment] 2019-10-25 08:21
@yojiyojiyoji What is the status update on this ?

**Comment by yojiyojiyoji** [comment] 2019-12-06 06:18
Actually, I have basically suspended this project, since I don't think I will release the plugin without libraries embedded.

**Comment by pcav** [comment] 2019-12-06 06:35
Sorry to hear that. Any way to find a better solution?

On 6 December 2019 07:18:54 CET, yojiyojiyoji <notifications@github.com> wrote:
>Actually, I have basically suspended this project, since I don't think
>I will release the plugin without libraries embedded.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/yojiyojiyoji/oam_qgis3_express/issues/1#issuecomment-562448225

-- 
Please excuse my brevity.

**Comment by yojiyojiyoji** [comment] 2019-12-06 07:14
The problem is that I doubt if I can have a constructive discussion, since the communication does not seem to be established. (It seems that you don't really understand what I am saying.) 
So, I will close this issue. 
If I have time, I will directly send you email later, but not sure when, or even if I can really do it.

**Closed as completed by yojiyojiyoji** 2019-12-06 07:14 UTC

**Comment by pcav** [comment] 2019-12-08 11:08
I'm really sorry for this reply. I am dealing with over 1k plugins, and we never had anything similar, being able to solve all issues for the common good.

**Comment by yojiyojiyoji** [comment] 2021-04-30 03:12
Hi @NyakudyaA @gabrielmancilla @koyo-jakanees
If necessary, you can download the plugin package file at:
https://github.com/yojiyojiyoji/oam_qgis3_express/releases
